# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 schedule:
   - cron: '0 0 * * 0'
 workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git config
        run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: | 
          git remote add upstream https://github.com/liquidslr/system-design-notes.git
          git fetch upstream
          git remote show upstream

      - name: Update current branch
        run: | 
          git checkout main
          git merge upstream/main

      - name: Push changes to fork
        run: | 
          git push origin main
